language: node_js
node_js:
  - "6"
  - "7"
cache:
  directories:
    - node_modules
script:
  - node index.js test-component && test -f test-component/package.json && echo Successfully created test-component
